Brunner/src/main/java/cz/uhk/ppro/dto/dtoLap.java
package cz.uhk.ppro.dto;


import cz.uhk.ppro.entity.Lap;
import cz.uhk.ppro.utils.FormatUtils;

import javax.persistence.Transient;
import java.time.Duration;

public class dtoLap {

    private int order;
    private float distanceMeters;
    private boolean complete;
    private Duration duration;
    private Duration pace;

    public dtoLap(){}

    public dtoLap(Lap lap){
        this.order = lap.getOrder();
        this.complete = lap.isComplete();
        this.duration = lap.getDuration();
        this.pace = lap.getPace();
        this.distanceMeters = lap.getDistanceMeters();
    }

    @Transient
    public String getDurationString() {
        return FormatUtils.convertDurationToStringHHmmss(duration);
    }
    @Transient
    public String getPaceString() {
        return FormatUtils.convertDurationToStringMMss(pace);
    }


    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public float getDistanceMeters() {
        return distanceMeters;
    }

    public void setDistanceMeters(float distanceMeters) {
        this.distanceMeters = distanceMeters;
    }

    public boolean isComplete() {
        return complete;
    }

    public void setComplete(boolean complete) {
        this.complete = complete;
    }

    public Duration getPace() {
        return pace;
    }

    public void setPace(Duration pace) {
        this.pace = pace;
    }

    public Duration getDuration() {
        return duration;
    }

    public void setDuration(Duration duration) {
        this.duration = duration;
    }

    public int getPaceHours(){
        return (int) pace.toHours();
    }

    public int getPaceMinutes(){
        return (int) pace.minusHours(getPaceHours()).toMinutes();
    }

    public int getPaceSeconds(){
        return (int) pace.minusHours(getPaceHours()).minusMinutes(getPaceMinutes()).getSeconds();
    }

    @Override
    public String toString() {
        return "Lap: " + order + " distance: " + distanceMeters + " time: " + FormatUtils.convertDurationToStringHHmmss(duration) + " complete? " + complete;
    }


}

Brunner/src/main/java/cz/uhk/ppro/entity/Lap.java
package cz.uhk.ppro.entity;

import cz.uhk.ppro.utils.FormatUtils;
import cz.uhk.ppro.utils.GPSProcessor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.time.Duration;
import java.time.format.DateTimeFormatter;


@Entity
@Table( name="lap" )
public class Lap  implements java.io.Serializable {

    public interface ValidationLap { }

    private int id;
    public enum Type {
        m500("500 m"),
        m1000("1000 m"),
        m2000("2000 m");
        private String value;

        Type(String value) { this.value = value; }

        public String getValue() {return value;}

        @Override
        public String toString() {
            return this.getValue();
        }
        public static Type getEnum(String value) {
            for(Type v : values())
                if(v.getValue().equalsIgnoreCase(value)) return v;
            throw new IllegalArgumentException();
        }
    }
    private Type type;
    private int order;
    private boolean complete;
    private Duration duration;
    private float distanceMeters;

    private Duration pace;
    private float elevationGained;
    private int heartRateAvg;

    private Training training;


    @Id
    @Column( name = "id_lap", nullable = false, unique = true )
    @GeneratedValue( strategy = GenerationType.IDENTITY )
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_training")
    public Training getTraining() { return training; }
    public void setTraining(Training training) { this.training = training; }


    @NotNull( groups = {ValidationLap.class} )
    @Column ( name = "type", nullable = false )
    @Enumerated( EnumType.STRING )
    public Type getType() { return type; }
    public void setType(Type type) { this.type = type; }


    @NotNull( groups = {ValidationLap.class} )
    @Column ( name = "lap_order" )
    public int getOrder() { return order; }
    public void setOrder(int order) { this.order = order; }


    @NotNull( groups = {ValidationLap.class} )
    @Column ( name = "complete" )
    public boolean isComplete() { return complete; }
    public void setComplete(boolean complete) { this.complete = complete; }


    @NotNull( groups = {ValidationLap.class} )
    @Column( name = "duration", nullable = false )
    @Convert( converter= cz.uhk.ppro.utils.DurationToStringConverter.class )
    public Duration getDuration() { return duration; }
    public void setDuration(Duration duration) { this.duration = duration; }


    @NotNull( groups = {ValidationLap.class} )
    @Column( name = "distance", nullable = false  )
    public float getDistanceMeters() { return distanceMeters; }
    public void setDistanceMeters(float distanceMeters) { this.distanceMeters = distanceMeters; }


    @Column( name = "pace_avg" )
    @Convert( converter= cz.uhk.ppro.utils.DurationToStringConverter.class )
    public Duration getPace() { return GPSProcessor.getAveragePace(duration, distanceMeters); }
    public void setPace(Duration pace) { this.pace = pace; }


    @Column( name = "elevation_gained" )
    public float getElevationGained() { return elevationGained; }
    public void setElevationGained(float elevationGained) { this.elevationGained = elevationGained; }


    @Column( name = "heart_rate_avg" )
    public int getHeartRateAvg() { return heartRateAvg; }
    public void setHeartRateAvg(int heartRateAvg) { this.heartRateAvg = heartRateAvg; }


    @Override
    public String toString() {
        return "Lap: " + order + " type: " + type.name() + " distance: " + distanceMeters + " time: " + FormatUtils.convertDurationToStringHHmmss(duration) + " complete? " + complete;
    }


    public Lap(){
        id = 0;
        type = Type.m1000;
        order = 0;
        complete = false;
        duration = Duration.ZERO;
        distanceMeters = 0;
        pace = Duration.ZERO;
        elevationGained = 0;
        heartRateAvg = 0;
        training = new Training();

    }

    public Lap(int order, Duration duration, float distanceMeters, float elevationGained, int heartRateAvg, Duration pace, boolean complete, Training training) {
        this();
        this.order = order;
        this.duration = duration;
        this.distanceMeters = distanceMeters;
        this.elevationGained = elevationGained;
        this.heartRateAvg = heartRateAvg;
        this.pace = pace;
        this.complete = complete;
        this.training = training;
    }



}

Brunner/src/main/java/cz/uhk/ppro/entity/Training.java
package cz.uhk.ppro.entity;

import cz.uhk.ppro.dto.dtoGPXTraining;
import cz.uhk.ppro.utils.FormatUtils;
import cz.uhk.ppro.dto.dtoManualTraining;
import org.springframework.format.annotation.DateTimeFormat;
import cz.uhk.ppro.utils.*;


import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table( name="training" )
public class Training implements java.io.Serializable {


    public interface ValidationTraining { }

    private int id;
    public enum Type { MANUAL, GPS }
    private Type type;
    private Date date;
    private String name;
    private String description;
    private Duration duration;
    private Duration pace;
    private Integer distanceMeters;
    private Integer distanceMetersAscent;
    private Integer distanceMetersDescent;
    private Integer elevationGained;
    private Integer elevationAscent;
    private Integer elevationDescent;
    private Integer elevationMin;
    private Integer elevationMax;
    private Integer heartRateAvg;
    private Integer heartRateMax;

    private User user;
    private List<Segment> track;
    private List<Point> points;
    private List<Lap> laps;
    private List<Record> records;

    @Transient
    private int sumHeartRate;



    @Id
    @Column ( name = "id_training", nullable = false, unique = true )
    @GeneratedValue( strategy = GenerationType.IDENTITY )
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_user")
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "training")
    public List<Segment> getTrack() { return track; }
    public void setTrack(List<Segment> track) { this.track = track; }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "training")
    public List<Point> getPoints() { return points; }
    public void setPoints(List<Point> points) { this.points = points; }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "training")
    public List<Lap> getLaps() { return laps; }
    public void setLaps(List<Lap> laps) { this.laps = laps; }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "training")
    public List<Record> getRecords() { return records; }
    public void setRecords(List<Record> records) { this.records = records; }


    @NotNull( groups = {ValidationTraining.class} )
    @DateTimeFormat( pattern="dd.MM.yyyy" )
    @Column( name = "date", nullable = false, columnDefinition="DATETIME" )
    public Date getDate() { return date;  }
    public void setDate(Date date) { this.date = date; }


    @NotNull( groups = {ValidationTraining.class} )
    @Column ( name = "type", nullable = false )
    @Enumerated( EnumType.STRING )
    public Type getType() { return type; }
    public void setType(Type type) { this.type = type; }


    @Size( max = 50, groups = {ValidationTraining.class} )
    @Column( name = "name" )
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }


    @Size( max = 500, groups = {ValidationTraining.class} )
    @Column( name = "description" )
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }


    @NotNull( groups = {ValidationTraining.class} )
    @Column( name = "duration", nullable = false )
    @Convert( converter= cz.uhk.ppro.utils.DurationToStringConverter.class )
    public Duration getDuration() { return duration; }
    public void setDuration(Duration duration) { this.duration = duration; }


    @NotNull( groups = {ValidationTraining.class} )
    @Min( value = 1 )
    @Column( name = "distance", nullable = false  )
    public Integer getDistanceMeters() { return distanceMeters; }
    public void setDistanceMeters(Integer distanceMeters) { this.distanceMeters = distanceMeters; }


    @NotNull( groups = {ValidationTraining.class} )
    @Column( name = "pace_avg" )
    @Convert( converter= cz.uhk.ppro.utils.DurationToStringConverter.class )
    public Duration getPace() { return GPSProcessor.getAveragePace(duration, distanceMeters); }
    public void setPace(Duration pace) { this.pace = pace; }


    @Column( name = "distance_ascent" )
    public Integer getDistanceMetersAscent() { return distanceMetersAscent; }
    public void setDistanceMetersAscent(Integer distanceMetersAscent) { this.distanceMetersAscent = distanceMetersAscent; }


    @Column( name = "distance_descent" )
    public Integer getDistanceMetersDescent() { return distanceMetersDescent; }
    public void setDistanceMetersDescent(Integer distanceMetersDescent) { this.distanceMetersDescent = distanceMetersDescent; }


    @Column( name = "elevation_gained" )
    public Integer getElevationGained() { return elevationGained; }
    public void setElevationGained(Integer elevationGained) { this.elevationGained = elevationGained; }


    @Column( name = "elevation_ascent" )
    public Integer getElevationAscent() { return elevationAscent; }
    public void setElevationAscent(Integer elevationAscent) { this.elevationAscent = elevationAscent; }


    @Column( name = "elevation_descent" )
    public Integer getElevationDescent() { return elevationDescent; }
    public void setElevationDescent(Integer elevationDescent) { this.elevationDescent = elevationDescent; }


    @Column( name = "elevation_min" )
    public Integer getElevationMin() { return elevationMin; }
    public void setElevationMin(Integer elevationMin) { this.elevationMin = elevationMin; }


    @Column( name = "elevation_max" )
    public Integer getElevationMax() { return elevationMax; }
    public void setElevationMax(Integer elevationMax) { this.elevationMax = elevationMax; }


    @Column( name = "heart_rate_avg" )
    public Integer getHeartRateAvg() { return heartRateAvg; }
    public void setHeartRateAvg(Integer heartRateAvg) { this.heartRateAvg = heartRateAvg; }


    @Column( name = "heart_rate_max" )
    public Integer getHeartRateMax() { return heartRateMax; }
    public void setHeartRateMax(Integer heartRateMax) { this.heartRateMax = heartRateMax; }



    @Transient
    public String getDurationString() {
        return FormatUtils.convertDurationToStringHHmmss(duration);
    }
    @Transient
    public String getPaceString() {
        return FormatUtils.convertDurationToStringMMss(pace);
    }


    public Training() {
        track = new ArrayList<>();
        elevationGained = 0;
        elevationAscent = 0;
        elevationDescent = 0;
        elevationMax = 0;
        elevationMin = 0;
        distanceMeters = 0;
        distanceMetersAscent = 0;
        distanceMetersDescent = 0;
        heartRateAvg = 0;
        heartRateMax = 0;
        sumHeartRate = 0;
        duration = Duration.ZERO;
        name = "";
        description = "";
        date = new Date();
    }

    public Training(dtoManualTraining dto){
        this();

        this.id = dto.getId();
        this.type = Type.MANUAL;
        this.date = dto.getDate();
        this.duration = dto.getDuration();
        this.distanceMeters = dto.getDistanceMeters();
        this.pace = GPSProcessor.getAveragePace(duration, distanceMeters);
        this.name = dto.getName();
        this.description = dto.getDescription();
        this.distanceMetersAscent = dto.getDistanceMetersAscent();
        this.distanceMetersDescent = dto.getDistanceMetersDescent();
        this.elevationGained = dto.getElevationGained();
        this.elevationAscent = dto.getElevationAscent();
        this.elevationDescent = dto.getElevationDescent();
        this.elevationMin = dto.getElevationMin();
        this.elevationMax = dto.getElevationMax();
        this.heartRateAvg = dto.getHeartRateAvg();
        this.heartRateMax = dto.getHeartRateMax();

    }


    public Training(dtoGPXTraining dto){
        this.id = dto.getId();
        this.type = Type.GPS;
        this.name = dto.getName();
        this.description = dto.getDescription();
        this.date = dto.getDate();
        this.heartRateAvg = dto.getHeartRateAvg();
        this.heartRateMax = dto.getHeartRateMax();
    }


    public void process() {
        int nodes = 0;
        for (Segment t : track) {
            t.process();
            nodes += t.getSegment().size();

            // distance
            distanceMeters += (int) t.getDistanceMeters();
            distanceMetersAscent += (int) t.getDistanceMetersAscent();
            distanceMetersDescent += (int) t.getDistanceMetersDescent();
            // duration
            duration = getDuration().plus(t.getDuration());
            // elevationGained
            elevationGained += (int) t.getElevationGained();
            elevationAscent += (int) t.getElevationAscent();
            elevationDescent -= (int) t.getElevationDescent(); // puvodne zaporne hodnoty - odecitam
            if ( t.getElevationMax() > elevationMax ) elevationMax = (int) t.getElevationMax();
            if ( t.getElevationMin() < elevationMin ) elevationMin = (int) t.getElevationMin();
            // heart rate
            sumHeartRate += t.getHeartRateSum();
            if (heartRateMax < t.getHeartRateMax()) {
                heartRateMax = t.getHeartRateMax();
            }
        }

        // pace
        pace = GPSProcessor.getAveragePace(duration, distanceMeters);

        // average heart rate
        heartRateAvg = sumHeartRate / nodes;
    }

    public Record getFastestDistance(float dist){

        Record best = new Record();

        if (distanceMeters < dist){
            return null;
        }

        Record r = new Record();
        boolean start = true;

        // projdi vsechny body
        for (Segment s : track) {
            for (Point t : s.getSegment()) {

Brunner/src/main/webapp/WEB-INF/views/trainings/all.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="tag" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<tiles:insertDefinition name="mainTemplate">

    <tiles:putAttribute name="title" value="All Trainings"/>

    <tiles:putAttribute name="body">

        <h1><spring:message code="trainings.h1" /></h1>

        <table class="table table-nobordered"
               id="table"
               data-toggle="table"
               data-unique-id="id"

               data-pagination="true"
               data-page-list="[5, 10, 20, 50, 100, 200]"
               data-search="true"

               data-show-columns="true"
               data-show-pagination-switch="true"
               data-show-export="true"

               data-mobile-responsive="true"
               data-check-on-init="true"

               data-advanced-search="true"
               data-id-table="advancedTable">
        <thead>

            <tr>
                <th data-field="id" data-sortable="true" class="hidden-md hidden-sm hidden-xs">#</th>

                <th data-field="date" data-sortable="true" data-sorter="dateTimeSorter" ><spring:message code="trainings.date" /></th>

                <th data-field="name" data-sortable="true"><spring:message code="trainings.name" /></th>

                <th data-field="distance" data-sortable="true"><spring:message code="trainings.distance" /></th>

                <th data-field="duration" data-sortable="true"><spring:message code="trainings.duration" /></th>

                <th data-field="pace" data-sortable="true"><spring:message code="trainings.pace" /></th>

                <th data-field="type">&nbsp;</th>

                <th data-searchable="false">&nbsp;</th>
                <th data-searchable="false">&nbsp;</th>
                <th data-searchable="false">&nbsp;</th>

            </tr>

        </thead>

        <tbody>

        <c:forEach items="${trainings}" var="training">
            <tr>

                <td>${training.id}</td>

                <td><fmt:formatDate value="${training.date}" pattern="dd.MM.yyyy"/></td>

                <td>${training.name}</td>

                <td>${training.distanceMeters} m</td>

                <td>${training.durationString}</td>

                <td>${training.paceString} min/km</td>

                <td>
                    <c:set var="type" scope="session" value="${training.type}"/>
                    <c:choose>
                        <c:when test="${type =='GPS'}">
                            <a data-placement="top" data-toggle="tooltip" title="Show map"
                               href="<c:url value='/trainings/map/${training.id}' />"
                               class="btn btn-primary btn-xs">
                                <span class="fa fa-globe"></span>
                            </a>
                        </c:when>

                        <c:otherwise>
                            &nbsp;
                        </c:otherwise>
                    </c:choose>
                </td>

                <td>
                    <a data-placement="top" data-toggle="tooltip" title="Detail"
                       class="btn btn-primary btn-xs"
                       href="<c:url value='/trainings/detail/${training.id}' />">
                        <span class="fa fa-line-chart"></span>
                    </a>
                </td>


                <c:choose>
                    <c:when test="${training.type.name() == 'GPS'}">
                        <td>
                            <a data-placement="top" data-toggle="tooltip" title="Edit"
                               class="btn btn-primary btn-xs"
                               href="<c:url value='/trainings/editGPS/${training.id}' />">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </td>
                    </c:when>

                    <c:otherwise>
                        <td>
                            <a data-placement="top" data-toggle="tooltip" title="Edit"
                               class="btn btn-primary btn-xs"
                               href="<c:url value='/trainings/edit/${training.id}' />">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </td>

                    </c:otherwise>
                </c:choose>


                <td>
                    <a data-placement="top" data-toggle="tooltip" title="Delete"
                       class="btn btn-danger btn-xs ajax-delete-user"
                       href="<c:url value='/trainings/delete/${training.id}' />">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>

            </tr>
        </c:forEach>

        </tbody>

        </table>

        <c:if test="${self}">
            <p>
                <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.new.manual" />"
                   class="btn btn-primary btn-xs"
                   href="<c:url value='/trainings/new' />">
                    <span class="fa fa-map fa-2x"></span>&nbsp;
                    <span><spring:message code="trainings.new.manual" /></span> </a>

                <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.new.file" />"
                   class="btn btn-primary btn-xs"
                   href="<c:url value='/trainings/upload' />">
                    <span class="fa fa-globe fa-2x"></span>&nbsp;
                    <span><spring:message code="trainings.new.file" /></span>
                </a>
            </p>
        </c:if>

    </tiles:putAttribute>

    <tiles:putAttribute name="custom-scripts">
        <tag:tooltipInit/>

        <script>
            function dateTimeSorter(a, b) {
                var year1 = a.substring(6, 10) * 1;
                var year2 = b.substring(6, 10) * 1;
                if (year1 > year2) return 1;
                else if (year1 < year2) return -1;
                else {
                    var month1 = a.substring(3, 5) * 1;
                    var month2 = b.substring(3, 5) * 1;
                    if (month1 > month2) return 1;
                    else if (month1 < month2) return -1;
                    else {
                        var day1 = a.substring(0, 2) * 1;
                        var day2 = b.substring(0, 2) * 1;
                        if (day1 > day2) return 1;
                        else if (day1 < day2) return -1;
                        else {
                            return 0;
                        }
                    }
                }
            }
        </script>

    </tiles:putAttribute>

</tiles:insertDefinition>

Brunner/src/main/webapp/WEB-INF/views/trainings/detail.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<tiles:insertDefinition name="mainTemplate">

    <tiles:putAttribute name="header">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    </tiles:putAttribute>

    <tiles:putAttribute name="title" value="Training: ${training.name}" />

    <tiles:putAttribute name="body">

        <h1>${training.name} (<fmt:formatDate value="${training.date}" pattern="dd.MM.yyyy"/>)</h1>

            <div class="row">

                <div class="container-general-info col-md-6 col-xs-12">

                    <h2><spring:message code="trainings.general" /></h2>

                    <c:if test="${training.description != ''}">
                        <span><b><spring:message code="trainings.desc" />:</b></span>
                        <p>${training.description}</p>
                        <br>
                    </c:if>


                    <table class="table table-sm">
                        <tr>
                            <td><span class="fa fa-road"></span>&nbsp;</td>
                            <td><spring:message code="trainings.distance" /></td>
                            <td><b>${training.distanceMeters} m</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-clock-o"></span></td>
                            <td><spring:message code="trainings.duration" /></td>
                            <td><b>${training.durationString}</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-line-chart"></span></td>
                            <td><spring:message code="trainings.pace" /></td>
                            <td><b>${training.paceString} min/km</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-arrow-up"></span></td>
                            <td><spring:message code="trainings.distance.asc" /></td>
                            <td><b>${training.distanceMetersAscent} m</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-arrow-down"></span></td>
                            <td><spring:message code="trainings.distance.desc" /></td>
                            <td><b>${training.distanceMetersDescent} m</b></td>
                        </tr>

                        <tr>
                            <td>&nbsp;</td>
                            <td><spring:message code="trainings.elevation.gain" /></td>
                            <td><b>${training.elevationGained} m</b></td>
                        </tr>

                        <tr>
                            <td>&nbsp;</td>
                            <td><spring:message code="trainings.elevation.asc" /></td>
                            <td><b>${training.elevationAscent} m</b></td>
                        </tr>

                        <tr>
                            <td>&nbsp;</td>
                            <td><spring:message code="trainings.elevation.desc" /></td>
                            <td><b>${training.elevationDescent} m</b></td>
                        </tr>

                        <tr>
                            <td>&nbsp;</td>
                            <td><spring:message code="trainings.elevation.max" /></td>
                            <td><b>${training.elevationMax} m</b></td>
                        </tr>

                        <tr>
                            <td>&nbsp;</td>
                            <td><spring:message code="trainings.elevation.min" /></td>
                            <td><b>${training.elevationMin} m</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-heartbeat"></span></td>
                            <td><spring:message code="trainings.heart.avg" /></td>
                            <td><b>${training.heartRateAvg} bpm</b></td>
                        </tr>

                        <tr>
                            <td><span class="fa fa-heart"></span></td>
                            <td><spring:message code="trainings.heart.max" />&nbsp;</td>
                            <td><b>${training.heartRateMax} bpm</b></td>
                        </tr>

                    </table>

                </div>

            </div>

        </br>
        </br>

        <div class="row">

            <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.delete" />"
               class="btn btn-danger btn-lg"
               href="<c:url value='/trainings/delete/${training.id}' />">
                <span class="fa fa-trash"></span>
                <span><spring:message code="trainings.delete.button" /></span> </a>

            &nbsp;

            <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.delete" />"
               class="btn btn-warning btn-lg"
               href="<c:url value='/trainings/edit/${training.id}' />">
                <span class="fa fa-pencil"></span>
                <span><spring:message code="trainings.edit" /></span> </a>

            &nbsp;

            <c:choose>
                <c:when test="${self}">
                    <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.back" />"
                       class="btn btn-primary btn-lg"
                       href="<c:url value='/trainings/' />">
                        <span class="fa fa-heartbeat"></span>
                        <span><spring:message code="trainings.back" /></span> </a>
                </c:when>

                <c:otherwise>
                    <a data-placement="top" data-toggle="tooltip" title="<spring:message code="trainings.back" />"
                       class="btn btn-primary btn-lg"
                       href="<c:url value='/trainings/user/${ownerId}' />">
                        <span class="fa fa-heartbeat"></span>
                        <span><spring:message code="trainings.back" /></span> </a>
                </c:otherwise>

            </c:choose>

        </div>

    </tiles:putAttribute>

</tiles:insertDefinition>